name: Build and Push Microservices and Frontend to Docker Hub

on:
  push:
    branches:
      - features/orderFiles  # Se ejecutará solo en esta rama

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout del código
        uses: actions/checkout@v3

      - name: 🔑 Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🛠️ Construir y subir imágenes de microservicios
        run: |
          # Listado de microservicios y sus rutas
          SERVICES=(
            "appointment-service/create-appointment-service"
            "appointment-service/delete-appointment-service"
            "appointment-service/get-all-appointments-service"
            "appointment-service/get-appointment-service"
            "appointment-service/update-appointment-service"
            "auth-user-service"
            "doctor-service/create-doctor-service"
            "doctor-service/delete-doctor-service"
            "doctor-service/get-doctor-service"
            "doctor-service/get-doctors-service"
            "doctor-service/update-doctor-service"
            "medical-history-service/create-medical-history-service"
            "medical-history-service/delete-medical-history-service"
            "medical-history-service/get-medical-history"
            "medical-history-service/get-medical-history-by-name"
            "medical-history-service/update-medical-history-service"
            "patient-service/create-patient-service"
            "patient-service/delete-patient-service"
            "patient-service/get-patient-service"
            "patient-service/get-patients-service"
            "patient-service/update-patient-service"
            "user-service/create-user-service"
            "user-service/delete-user-service"
            "user-service/get-all-users-service"
            "user-service/get-user-service"
            "user-service/update-user-service"
          )

          # Construir y subir cada microservicio
          for SERVICE in "${SERVICES[@]}"; do
            echo "🛠️ Construyendo $SERVICE en BACKEND/services/$SERVICE"
            docker build -t ${{ secrets.DOCKER_USERNAME }}/$SERVICE:latest ./BACKEND/services/$SERVICE
            echo "⬆️ Subiendo $SERVICE a Docker Hub"
            docker push ${{ secrets.DOCKER_USERNAME }}/$SERVICE:latest
          done
